### ISSUE TITLE
[Feature Request]Add a "duration in minutes" variable to the response builder.

### ISSUE THREAD

**Issue by seanchilds** [tonesto7/echo-speaks#179]
**Is your feature request related to a problem? Please describe.**
I wanted a reminder that a door was left open and it would be nice to also have it state how long the door has been open for.
This is easily done with the duration variable but this is in seconds.

**Describe the solution you'd like**
if there was a "duration in minutes" variable then it would say 'the front door has been open for 30 minutes' instead of 1,892 seconds.

**Describe alternatives you've considered**
a duration without the word seconds being said and a math option available.
Door has been open {"duration"/60} minutes

**Additional context**

**Comment by seanchilds** [comment]
Thank you for adding this new variable! 

However, there appear to be a couple of small bugs in it.
1: When I enter this new variable in the Response Designer this variable is white in color not green like the other variables. (see below)
2: It is also adding a ".0 seconds ago" to the actual value. so the speech for the below response is.
"contact is now open 387 seconds ago or 6.0 seconds ago"

I also suggest that this Variable = "6 minutes" only because the decimal is always 0 and tho adding the 'ago' is very handy for most cases it also limits its possibilities.

example:
speech would be "contact is now open 387 seconds or 6 minutes"

![Screenshot_20191220-175247_SmartThings](https://user-images.githubusercontent.com/18430391/71325929-fca90200-24b0-11ea-8eca-fe12e89f35bf.jpg)

**Comment by tonesto7** [comment]
thanks for catching that.  I've pushed out a fix for the variable color format by changing the variable from %duration_min% to %durationmin%.

I've also corrected the .0 issue.

**Comment by seanchilds** [comment]
I am sorry to keep bugging you, but this is still not working correctly I
think trying to remove the .0 made things worse.
now it gives this error.
5:15:37 PM: error groovy.lang.MissingMethodException: No signature of
method: java.math.BigDecimal.round() is applicable for argument types:
(java.lang.Integer) values: [0]

The ".0" was really not a big deal the biggest problem before was that it
would say "10.0 seconds ago" when it had been 10 minutes.

Thank you!

**Comment by tonesto7** [comment]
@seanchilds I'm fixing this right now.  Check for an update after one hour.  It will  be the actions file only.

**Comment by tonesto7** [comment]
@seanchilds Sorry about that mess.  Did the latest update resolve your issues?

**Comment by seanchilds** [comment]
Yes the latest ver. has been working great.
Sorry, i was going to let you know  that it was working but i got
sidetracked.

Thanks!
