### ISSUE TITLE
Toggle for "Restrictions/Conditions

### ISSUE THREAD

**Issue by dbennett3321** [tonesto7/echo-speaks#884]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Hubitat
-  How many devices are detected?: 9
-  iOS or Android?: Android
-  Mobile App Version(Not required): 
-  App/SmartApp Version: v4.1.9.2
-  Device Handler/Driver Version: v4.1.9.2
-  Heroku Server Version: v2.7.0

## Expected Behavior
**Toggle for "Restrictions/Conditions":
     "Require All Selected Conditions to Pass Before Activating Zone?"
needs to save toggle option.
**

## Current Behavior

**Toggle for "Restrictions/Conditions": 
     "Require All Selected Conditions to Pass Before Activating Zone?"
is not updating to that action condition after saving the conditions page. It stays set on:
     "Any condition will allow this action to operate"
vs:
     "All selected conditions must pass before for this action to operate."
**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Create action with toggle on. 
2. Save Action 
3. Go back to edit 
4.Toggle will show flipped however text below stating current setting will be switched back to default. 

## Context
** When setting multiple conditions to include time parameters for actions the action will not suspend if parts of rule are not met. It will continue to run even if only one of the parameters are met.**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by dbennett3321** [comment]
(ACTIONS BUG) time restrictions not honored #314 

Seems to describe most of my issues as well. I tried redoing the rule entirely and creating another rule and still have the same issues.

**Comment by dbennett3321** [comment]
https://user-images.githubusercontent.com/87721039/127802877-103d14b5-6071-44ef-b255-a82b309e9962.mp4

**Comment by dbennett3321** [comment]
https://linksharing.samsungcloud.com/a5J8rjWWzPsz

**Comment by imnotbob** [comment]
if you try the current beta, this should be fixed (of ES)

**Comment by dbennett3321** [comment]
Do I use HPM for this and I have the toggle set for pre release software to be included. It says I don't have any updates available. I'm still having issues this morning. Do I need need to manually update this?

**Comment by dbennett3321** [comment]
I'm using V4.1.9.3 is this correct?

**Comment by imnotbob** [comment]
yes, there is a beta branch.

You can use HPM if matched to beta, or you can install by hand.

If HPM is not hooked to beta, you can delete HPM, re-install it, rematch, but match to beta version of Echo speaks

**Comment by randmiller** [comment]
Just FYI - this (can't toggle require **All** selected conditions) is still a problem in V4.1.9.4.

**Comment by dbennett3321** [comment]
Agreed still an issue makes this app completely unusable in my scenarios.

**Comment by tonesto7** [comment]
@imnotbob  I thought we resolved this 🤦
@randmiller @randmiller  Does it happen not matter which conditions types you have selected?
I’m curious if there are certain combos of conditions that are causing this issue.

I’m going to get this resolved and soon as we can track it down.

**Comment by randmiller** [comment]
Seems to be related to the toggle, I have quite a mix of conditions.
<img width="529" alt="Screen Shot 2021-08-18 at 8 39 12 PM" src="https://user-images.githubusercontent.com/18269885/130005125-9c972348-7ab5-484c-ad16-1348409e2979.png">

**Comment by dbennett3321** [comment]
correct you can change the toggle and it will reflect the change. however when you exit the rule after accepting the changes and go back to the apps section and reload the app and rule it will change back to "Any condition allowed"

**Comment by tonesto7** [comment]
@randmiller Thanks for the details.  I'm curious is the conditions flag actually working?  Is this just a UI issue where the text is not reflecting the true state?

**Comment by dbennett3321** [comment]
No it is not working

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tonesto7** [comment]
ok... I'm going to duplicate a zone with conditions the same as yours.  I think it might have something to one of the specific condition types.  
I created a new Zone with days of the week and SHM disarmed, and even after saving and returning to the zone the all conditions flag remained correct.

**Comment by dbennett3321** [comment]
Yes apply leave the app entirely go to the apps page and load

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by tonesto7** [comment]
In your screenshot you are referencing an action, does the same condition issue affect zones?

**Comment by tonesto7** [comment]
The good news is that I'm able to see the same thing in my test action.  It's working correctly on the Zones conditions.  

I will dive into this and get a fix out :)

**Comment by tonesto7** [comment]
@randmiller  @dbennett3321  I just pushed out v4.1.9.5 for all files.  This should resolve your issues

**Comment by dbennett3321** [comment]
Damn that's freaking awesome man I'll download it this morning and check it out

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by dbennett3321** [comment]
I have tested this and it does reflect properly. Thank you for your time and commitment to this community. Your a saint and a scholar sir!

**Comment by randmiller** [comment]
I've installed the latest and seems to have fixed things. Thanks so much!  I don't know about the saint and scholar, but you're definitely a wizard. 😉
