### ISSUE TITLE
(BUG) 

### ISSUE THREAD

**Issue by robertgoron88** [tonesto7/echo-speaks#90]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The App/SmartApp and Device Handler/Driver are using the latest code available.
-  [x ] You have reviewed the [Echo Speaks Documentation](https://tonesto7.github.io/echo-speaks-docs) for potential fixes.
-  [x ] That Both the Apps/SmartApps and Device Handlers/Drivers have been _Published for You_ in the IDE.

---
## About Your Setup
-  Hub Platform (SmartThings or Hubitat): Smartthings
-  How many devices are detected?: 0
-  iOS or Android?: Android
-  Mobile App Version(Not required):
-  App/SmartApp Version: 2.17.0 build number 448328
-  Device Handler/Driver Version: 2.5.2
-  Heroku Server Version:

## Expected Behavior
**tell us what should happen**
after giving amazon credential it would log in

## Current Behavior
**What happens instead of the expected behavior?**
after logging in with amazon account the web page jumps back to the login information. There is no authentication good

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. i had it installed once and it was working
2. it stopped with amazon cookie expired
3. deleted the smartapp and reinstalled it
4. when i´m trying to login with amazon account it doesn´t do it

## Context
**How has this issue affected you? What are you trying to accomplish? to use echo speaks
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug
![login](https://user-images.githubusercontent.com/50329049/59698168-be0a5600-91b4-11e9-9138-70caad11dcf7.png)

**Comment by brentokeeffe** [comment]
This appears to be the same problem I am experiencing.

**Comment by cloudedturtle** [comment]
@robertgoron88 - [Please check issue #92 for a possible solution.](https://github.com/tonesto7/echo-speaks/issues/92)

**Comment by tonesto7** [comment]
Hey said she was resolved in the latest server update

**Comment by hafizchin** [comment]
Hi,

First of all, thank you for this wonderful app.


After installing the latest version, I am still unable to login.

Issues:
1. using amazon.ca, the cookie is not captured.
2. using amazon.com, the cookie is captured and it says "Authentication Good". However when I go back to the app, it says "You still need to Login to Amazon to complete the setup". Please see screenshots below

![IMG_DCC9ED0B8BAF-1](https://user-images.githubusercontent.com/6478018/87852878-cced9b80-c8d3-11ea-9bde-73a8f351055c.jpeg)

![IMG_E9169478435E-1](https://user-images.githubusercontent.com/6478018/87852892-e4c51f80-c8d3-11ea-888e-ad01fa905b41.jpeg)

**Comment by Jmarcos13** [comment]
> Hi,
> 
> First of all, thank you for this wonderful app.
> 
> After installing the latest version, I am still unable to login.
> 
> Issues:
> 
> 1. using amazon.ca, the cookie is not captured.
> 2. using amazon.com, the cookie is captured and it says "Authentication Good". However when I go back to the app, it says "You still need to Login to Amazon to complete the setup". Please see screenshots below
> 
> ![IMG_DCC9ED0B8BAF-1](https://user-images.githubusercontent.com/6478018/87852878-cced9b80-c8d3-11ea-9bde-73a8f351055c.jpeg)
> 
> ![IMG_E9169478435E-1](https://user-images.githubusercontent.com/6478018/87852892-e4c51f80-c8d3-11ea-888e-ad01fa905b41.jpeg)

Have you manage how to resolve this?

**Comment by hafizchin** [comment]
Hi,

All is good now. The app is working as expected!

read [https://community.smartthings.com/t/release-echo-speaks-v3-actions/173073/986](url) and scroll to the latest comments.

**Comment by Jmarcos13** [comment]
> Hi,
> 
> All is good now. The app is working as expected!
> 
> read [https://community.smartthings.com/t/release-echo-speaks-v3-actions/173073/986](url) and scroll to the latest comments.

I don't get it what i'm doing wrong. I have logged now, but i end up in your situation...
I create the serve with the amazon.com domain, with my locate, then sign-in but even with all that, i end up in your error :(

**Comment by hafizchin** [comment]
Here's my config:

**App:**
Domain : select your correct domain (mine is amazon.ca)
Locale: select your correct locale (mine is en-CA)

**Heroku:**
when you deploy a new server modify the following config variables / or just update your existing server:
amazonDomain: amazon.com
regionLocale: your correct locale

Hope this helps.

**Comment by Jmarcos13** [comment]
> Here's my config:
> 
> **App:**
> Domain : select your correct domain (mine is amazon.ca)
> Locale: select your correct locale (mine is en-CA)
> 
> **Heroku:**
> when you deploy a new server modify the following config variables / or just update your existing server:
> amazonDomain: amazon.com
> regionLocale: your correct locale
> 
> Hope this helps.

Yeah, i done that... 
https://imgur.com/a/bBnTbwV

Don't know the reason why

> Here's my config:
> 
> **App:**
> Domain : select your correct domain (mine is amazon.ca)
> Locale: select your correct locale (mine is en-CA)
> 
> **Heroku:**
> when you deploy a new server modify the following config variables / or just update your existing server:
> amazonDomain: amazon.com
> regionLocale: your correct locale
> 
> Hope this helps.

Dude... Thank you a lot!!!! For real, i was missing a thing (feeling stupid now)

You, like everyone else, helped a lot, really gratefull

**Comment by hafizchin** [comment]
Glad it worked!!!
